version: '3.8'

services:
  service_1:
    build: ./service_1
    container_name: service_1
    expose:
      - "8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/ping"]
      interval: 10s
      retries: 3
    networks:
      - backend

  service_2:
    build: ./service_2
    container_name: service_2
    expose:
      - "5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/ping"]
      interval: 10s
      retries: 3
    networks:
      - backend

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - service_1
      - service_2
    networks:
      - backend

networks:
  backend:

